# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file
_commit: HEAD
_src_path: ../../hexdummy
author: artynova
capitalize_platforms: false
classname: HexDummy
default_branch: main
description: Hex Dummy addon for Hex Casting
display_name: Hex Dummy
github_repo: hexdummy
hexcasting_version: 0.10.3
homepage_url: https://artynova.github.io/hexdummy
initial_mod_version: 0.0.1
java_version: 17
license: MIT
mappings_name: Mojmap
modid: hexdummy
package: net.hexdummy
sources_url: https://github.com/artynova/hexdummy
