# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/updating/#never-change-the-answers-file-manually
_commit: HEAD
_src_path: ../../hexdummy
advanced: false
description: Hex Dummy addon for Hex Casting
display_name: Hex Dummy
github_repo: hexdummy
github_user: artynova
kotlin: true
mappings_name: Mojmap
minecraft_version: 1.20.1
modid: hexdummy
package: io.github.artynova.hexdummy
