# copier-template-tester configuration and default answers

[defaults]
modid = "hexdummy"
github_user = "FallingColors"
classname = "HexDummy"
display_name = "Hex Dummy"
mod_version = "0.1.0"

[output.".ctt/mojmap"]
mappings_name = "Mojmap"

[output.".ctt/yarn"]
mappings_name = "Yarn"

[output.".ctt/leading_number_username"]
mappings_name = "Mojmap"
github_user = "1leadingnum"
