# copier-template-tester configuration and default answers

[defaults]
modid = "hexdummy"
github_user = "artynova"
classname = "HexDummy"
display_name = "Hex Dummy"
minecraft_version = "1.20.1"

[output.".ctt/mojmap"]
mappings_name = "Mojmap"

[output.".ctt/yarn"]
mappings_name = "Yarn"
