name: Run tests

on:
  push:
    branches: "*"
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        java-version: [17]
        mappings: [mojmap, yarn]
        include:
          - os: ubuntu-latest
            java-version: 17
            upload: true
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      - name: Install Nox
        run: pip install nox

      - name: Copy template
        run: nox -s ctt

      - uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: .ctt/${{ matrix.mappings }}

      - name: Run tests
        run: nox -k ${{ matrix.mappings }}

      - name: Upload full rendered project artifact
        if: matrix.upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.mappings }}-example-all
          path: .ctt/${{ matrix.mappings }}/

      - name: Upload build artifact
        if: matrix.upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.mappings }}-example-build
          path: .ctt/${{ matrix.mappings }}/*/build/libs/*.jar
